export const BASE_URL = 'https://'+ getContext(this).resourceManager.getStringSync($r('app.string.baseurl').id)

export const url = 'https://'+ getContext(this).resourceManager.getStringSync($r('app.string.url').id)

export const sampleSet = 'https://'+ getContext(this).resourceManager.getStringSync($r('app.string.sampleSet').id)

export const auth_url = 'https://'+ getContext(this).resourceManager.getStringSync($r('app.string.authurl').id)